apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
      - name: grpc-client
        image: your-registry/grpc-client:latest
        env:
        - name: GRPC_SERVER_HOST
          value: "grpc-server"
        - name: GRPC_SERVER_PORT
          value: "50051"
