version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install grpcio grpcio-tools

  build:
    commands:
      - terraform init
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
